import Head from 'next/head'
import Image from 'next/image'
import {CssBaseline,Grid} from '@material-ui/core'
import Header from '../components/Header/Header'
import Map from '../components/Map/Map'
import List from '../components/List/List'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline/>
      <Header/>
      <Grid container spacing={3} style={{width: '100%'}}>
        <Grid item xs={12} md={4}>
          <List/>
        </Grid>
        <Grid item xs={12} md={4}>
          <Map/>
        </Grid>
      </Grid>
    </>
  )
}
